services:
  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./Backend
    container_name: backend-container
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/GodTreningDB
    depends_on:
      - mongo

  frontend:
    build: ./Frontend
    container_name: frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
